# Generated by Django 5.0.2 on 2025-06-15

from django.db import migrations, models


def parse_route_hex(route_hex):
    from gui.lnd_deps import lightning_pb2 as ln
    parsed = ln.Route()
    parsed.ParseFromString(bytes.fromhex(route_hex))
    return parsed


def normalize_routes(apps, schema_editor):
    RebalanceRoute = apps.get_model('gui', 'RebalanceRoute')
    for rr in RebalanceRoute.objects.all():
        try:
            parsed = parse_route_hex(rr.route)
            path = '-'.join(h.pub_key for h in parsed.hops)
            if len(parsed.hops) >= 2:
                cltv = parsed.hops[-1].expiry - parsed.hops[-2].expiry
            else:
                cltv = 144
            existing = RebalanceRoute.objects.filter(
                target_pubkey=rr.target_pubkey,
                outgoing_chan_id=rr.outgoing_chan_id,
                route=path,
            ).exclude(id=rr.id).first()
            if existing:
                existing.success_count += rr.success_count
                existing.failure_count += rr.failure_count
                if rr.last_success and (
                    not existing.last_success or rr.last_success > existing.last_success
                ):
                    existing.last_success = rr.last_success
                if rr.last_failure and (
                    not existing.last_failure or rr.last_failure > existing.last_failure
                ):
                    existing.last_failure = rr.last_failure
                existing.final_cltv_delta = cltv
                existing.save()
                rr.delete()
            else:
                rr.route = path
                rr.final_cltv_delta = cltv
                rr.save(update_fields=['route', 'final_cltv_delta'])
        except Exception:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0039_inboundfeelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebalanceRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_pubkey', models.CharField(max_length=66)),
                ('outgoing_chan_id', models.CharField(max_length=20)),
                ('route', models.TextField()),
                ('final_cltv_delta', models.IntegerField(default=144)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_success', models.DateTimeField(default=None, null=True)),
                ('last_failure', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'unique_together': {('target_pubkey', 'outgoing_chan_id', 'route')},
                'indexes': [
                    models.Index(
                        fields=['target_pubkey', 'outgoing_chan_id'],
                        name='rebalroute_target_out_idx',
                    )
                ],
            },
        ),
        migrations.RunPython(normalize_routes, migrations.RunPython.noop),
    ]

    atomic = False
