# Generated by Django 5.0.2 on 2025-06-16
from django.db import migrations, models


def copy_hex(apps, schema_editor):
    RebalanceRoute = apps.get_model('gui', 'RebalanceRoute')
    for rr in RebalanceRoute.objects.all():
        try:
            bytes.fromhex(rr.route)
        except ValueError:
            continue
        rr.route_hex = rr.route
        rr.save(update_fields=["route_hex"])


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0040_rebalanceroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebalanceroute',
            name='route_hex',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(copy_hex, migrations.RunPython.noop),
    ]

    atomic = False
